api.v1.account:
  path: /account
  controller: App\Controller\Users\AccountController::accountApi
  methods: GET

api.v1.note.new:
  path: /note/new
  controller: App\Controller\Notes\NotesController::newNote
  methods: POST

api.v1.note.getByUuid:
  path: /note/uuid/{uuid}
  controller: App\Controller\Notes\NotesController::getNoteByUuid
  methods: GET
  requirements:
    uuid: '[a-fA-F0-9\-]+'

api.v1.note.upsert:
  path: /note/uuid/{uuid}
  controller: App\Controller\Notes\NotesController::upsertNote
  methods: PUT
  requirements:
    uuid: '[a-fA-F0-9\-]+'

api.v1.note.deleteByUuid:
  path: /note/uuid/{uuid}
  controller: App\Controller\Notes\NotesController::deleteNoteByUuid
  methods: DELETE
  requirements:
    uuid: '[a-fA-F0-9\-]+'

api.v1.note.list:
  path: /note/list
  controller: App\Controller\Notes\NotesController::getNoteList
  methods: GET

api.v1.note.export:
  path: /note/export
  controller: App\Controller\Notes\NotesController::getNotesForUser
  methods: GET

api.v1.workspace.getByUuid:
  path: /workspace/uuid/{uuid}
  controller: App\Controller\Notes\NotesController::getWorkspaceByUuid
  methods: GET
  requirements:
    uuid: '[a-fA-F0-9\-]+'
