api.v1.account:
  path: /account
  controller: App\Controller\Users\AccountController::accountApi
  methods: GET

api.v1.note.getByClientUuid:
  path: /note/client-uuid/{uuid}
  controller: App\Controller\Notes\NotesController::getNoteByClientUuid
  methods: GET
  requirements:
    uuid: '[a-fA-F0-9\-]+'

api.v1.note.deleteByClientUuid:
  path: /note/client-uuid/{uuid}
  controller: App\Controller\Notes\NotesController::deleteNoteByClientUuid
  methods: DELETE
  requirements:
    uuid: '[a-fA-F0-9\-]36'

api.v1.note.list:
  path: /note/list
  controller: App\Controller\Notes\NotesController::getNoteList
  methods: GET

api.v1.note.export:
  path: /note/export
  controller: App\Controller\Notes\NotesController::getNotesForUser
  methods: GET

api.v1.note.upsert:
  path: /note/upsert
  controller: App\Controller\Notes\NotesController::upsertNote
  methods: PUT
