api.v1.account:
  path: /account
  controller: App\Controller\Users\AccountController::accountApi
  methods: GET

api.v1.note.getByClientUuid:
  path: /note/clientUuid/{uuid}
  controller: App\Controller\Notes\NotesController::getNoteByClientUuid
  methods: GET
  requirements:
    uuid: '[a-zA-Z0-9\-]36'

api.v1.note.list:
  path: /note/list
  controller: App\Controller\Notes\NotesController::getNoteList
  methods: GET

api.v1.note.upsert:
  path: /note/upsert
  controller: App\Controller\Notes\NotesController::upsertNote
  methods: PUT
