account.create:
  path: /create
  controller: App\Controller\Users\AccountController::form
  methods: GET

account.create.save:
  path: /create
  controller: App\Controller\Users\AccountController::create
  methods: POST

account.edit.save:
  path: /edit
  controller: App\Controller\Users\AccountController::edit
  methods: POST

account.profile:
  path: /
  controller: App\Controller\Users\AccountController::index

account.workspace.registrationSuccess:
  path: /registration-success
  controller: App\Controller\Users\AccountController::workspaceRegistration

account.workspace.delete:
  path: /workspace/{uuid}
  controller: App\Controller\Users\AccountController::workspaceDelete
  methods: DELETE
  requirements:
    uuid: '[a-fA-F0-9\-]+'
