name: Noted Checks & Release

on:
  pull_request:
    branches:
      - main

jobs:
  build-php:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP74
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: php-xml

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          php-version: '7.4'
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run all checks
        run: composer run-script php-lint

  cache-node-dependencies:
    needs: build-php
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Cache NPM packages
        id: npm-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npx yarn install --check-cache

  asset-linting:
    needs: cache-node-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install NPM Packages
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npx yarn install --check-cache

      - name: Linting
        run: npx yarn run lint-all
